echo "🚀 PUSH TO GITHUB - Replace 'yourusername' with your actual GitHub username"
echo ""
echo "Step 1: Set your GitHub repository URL"
echo "git remote set-url origin https://github.com/YOURUSERNAME/ayurvedic-clinic-app.git"
echo ""
echo "Step 2: Push to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Step 3: Your clinic app will be live on GitHub!"
echo ""
echo "🌐 DEPLOY TO CLOUD:"
echo "1. Go to render.com"
echo "2. New -> Web Service"
echo "3. Connect your GitHub repository"
echo "4. Deploy!"
echo ""
pause